# Generated by Django 3.2.4 on 2021-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
