# Generated by Django 3.2.4 on 2021-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_add_job_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
