# Generated by Django 3.2.4 on 2021-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_job_salary_median'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unix_activation_date',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
